config/routes.rb
Samapp::Application.routes.draw do
  

resources :questions do
	resources :answers
end
devise_for :users

  root :to => 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
has_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
#class AnswersController < ApplicationController
before_filter :find_question
before_filter :find_ans,:only => [:show]
def index
	@answer=@question.Answer.all
end
	def new
	@answer=@question.answers.build
	end
	def create
    @answer = @question.answers.build(params[:answer])
    if @answer.save
      flash[:notice] = "Ticket has been created."
      redirect_to [@question, @answer]
    else
      flash[:alert] = "Ticket has not been created."
      render :action => "new"
    end
    def show
    	 
    end
  end
	  private
    def find_question
      @question = Question.find(params[:question_id])
      # @question = Question.find(params[:comment])
    end
    def find_ans
    @answer = @question.answers.find(params[:id])
    	 logger.warn("==========#{@answer.inspect}")
    	 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  protected
  
  def set_current_user
    if session[:user_id] 
           @current_user = User.find(session[:user_id])
       else
           @current_user = nil
       end
  end
  
  def login_required
    if @current_user.nil?
         redirect_to root_path,:notice => "login required"    
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
def index
		@question=Question.all
		@user = User.find(:all)
		respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @question }
    end
	end

	def new
		@question=Question.new
	end
	def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @question }
    end
  end
	def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, :notice=> 'User was successfully created.' }
        format.json { render :json => @question, :status => created, :location=> @question }
      else
        format.html { render :action=> "new" }
        format.json { render :json => @question.errors, :status=> unprocessable_entity }
      end
    end
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.erb
<%= form_for [ @question, @answer ] do |f| %>

  <p>
    <label>comment</label>
    <%= f.text_area :comment%>
  </p>
  <%= f.submit %>
<% end %>

app/views/answers/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/answers/show.html.erb
<p>
  <b>Answer:</b>
  <%= @answer.comment %>
  </p>





<%= link_to 'Back', questions_path %>

app/views/comman/_footer.html.erb
<%= link_to "Contact US", root_path %>

app/views/comman/_header.html.erb
<div style="float:left;font-size: 20pt; font-family: verdana;line-height: 30px;"><%= link_to "Home", root_path %></div>
<div class="subnav" style=" font-size: 20pt; font-family: verdana; line-height: 30px;"> 
  <% if user_signed_in? %>
     <div class="page-header" style="padding-left:700px;">  Signed in as <%= current_user.email %>
     <%#= link_to "Sign out",destroy_user_session_path,:method => :delete %>
  <% else %>
    <div class="page-header" style="padding-left:1000px;">  <%= link_to "Sign up",new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %></div> 
   <% end %>
</div>
      
      
      

app/views/comman/_tab.html.erb
<div class="page-header" style="text-align:center;">
<div class="btn btn-primary btn-large">Ruby on Rails</div>
<div class="btn btn-success btn-large">PHP</div>
<div class="btn btn-warning btn-large">C/C++</div>
<div class="btn btn-danger btn-large">.NET</div>
<div class="btn btn-inverse btn-large">Android</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Samapp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial=>'comman/header' %>
<%= yield %>
<div class="modal-footer" style="margin-bottom:20px;">
<%= render :partial=>'comman/footer' %>
</div>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label>Question  </label>
    <%= f.text_field :name %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/index.html.erb
<% if current_user %>
<%= render :partial=>'comman/tab' %>

<table>
  <tr>
    <th>Question</th>
   
  </tr>

<% @question.each do |question| %>
  <tr>
    <td><%= question.name %></td>
    <td><%= link_to 'Show', question %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Answer',question_answers_path(@question)%>
<%= link_to 'Create Question', new_question_path %>

<br><br><br><br><br><br>
<% else %>
<h2 class="alert alert-success "style="border:medium solid;"><div class="btn-inverse btn-large" style="padding-top:100px;padding-bottom:100px;font-size:30pt;border:medium solid;"><marquee>QUESTION ANSWER SYSTEM</marquee></div></h2>
<br><br><br><br><br><br>
<% end %>

app/views/questions/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p>
  <b>Question:</b>
  <%= @question.name %>
  </p>




<%= link_to 'Answer', new_question_answer_path(@question)%>
<%= link_to 'Back', questions_path %>